### ISSUE TITLE
Show context in cell status bar even when cell execution fails

### ISSUE THREAD

**Issue by pgfearo** [DeltaXML/vscode-xpath-notebook#3]
This can be used (awaiting VS Code upstream fix) to provide a command to set the context and evaluate the cell again with the new context

**Comment by pgfearo** [comment]
Done

**Comment by RandomFractals** [comment]
do you have a pic of how it looks in vscode? I've been considering maybe adding some status bar items to my data table renderer too for errors and loaded data stats display. 

My context is limited because I only provide cell output render, but I am interested in exploring that setup more. Linking to my open data table renderer status display issue, if you don't mind, so I can revisit your changes later: https://github.com/RandomFractals/vscode-data-table/issues/64

**Comment by pgfearo** [comment]
The cell status bar can be seen at the bottom of the XPath code cell below. Where it says `Source: gdpByCountry.xml` and `Items: 5`

![xpath-notebook](https://user-images.githubusercontent.com/2734234/127873033-5ce2c3b7-879f-4e51-9473-9caa4072140e.png)

Note that there's a known bug (in GitHub VSCode issues) that means you can't add a command object to a status bar item, only a command string. So I don't think you can pass any arguments to a command at the moment.

**Comment by RandomFractals** [comment]
Oh, that's really nice! I'll have to check if I have access to that context in renderer api too. Thanks for sharing that pic!

**Comment by pgfearo** [comment]
It's a CellStatusBarItemProvider, so you should be able to register one for your renderer.
