### ISSUE TITLE
Line breaks in string literal

### ISSUE THREAD

**Issue by martin-honnen** [DeltaXML/vscode-xpath-notebook#6]
While playing with the XPath notebook I found that a sample like
```
let $xml1 := parse-xml('<root>
  <item>a</item>
  <item>b</item>
</root>')
return $xml1/root/item
```
runs fine but syntax errors are displayed for the second, third line and fourth line: "unexpected token".
That raises the question whether line breaks in XPath string literals are allowed, I think they are allowed.

**Comment by pgfearo** [comment]
Thanks for reporting this bug.

Before actually looking at the code my feeling is that this is related to
the fact that the problem reporter uses the same  tokens as the 'semantic
highlighter'.

In VSCode, semantic highlighter tokens must be split to prevent a token
spanning more than one line, I'm guessing the problem reporter isn't taking
this token splitting into account .

I'll report back once I've learned more.

**Comment by pgfearo** [comment]
The root cause of this is that there is code that doesn't handle multi-line string tokens that must be split so there is just one token per line. The affected code is actually in the lexer and diagnostics features in our XSLT/XPath extension that the XPath Notebook extension uses.

Please track progress on this at: [vscode-xslt-tokenizer #92](https://github.com/DeltaXML/vscode-xslt-tokenizer/issues/92)
