### ISSUE TITLE
Cannot execute cell with error code FODC0002

### ISSUE THREAD

**Issue by jgonzalez-stw** [DeltaXML/vscode-xpath-notebook#8]
When executing a cell, the following error is displayed:

`XError:Cannot read file c:\Users\Jes%C3%BAs Gonz%C3%A1lez\.vscode\extensions\deltaxml.xpath-notebook-0.0.6\resources\xslt-sef\xpath-eval-to-json.sef.json - ENOENT: no such file or directory, open 'c:\Users\Jes%C3%BAs Gonz%C3%A1lez\.vscode\extensions\deltaxml.xpath-notebook-0.0.6\resources\xslt-sef\xpath-eval-to-json.sef.json'; code:FODC0002`

The referenced file is actually there. Probably the problem is related to the username directory having a space character and/or unicode characters.

**Comment by pgfearo** [comment]
Thanks for reporting this bug. I'll update this issue as soon as I've reproduced this locally and learnt more.

**Comment by jgonzalezdr** [comment]
I've just uploaded a PR (#9) that fixes the issue with a workaround.

The root cause is a bit obscure, because the dumped script was generated properly in the temp dir, and it executed just fine when running nodejs REPL outside vscode, but when run from the extension SaxonJS for some reason just did not handle properly multi-byte characters. This workaround avoids generating the path with multi-byte characters, and therefore circumvents the root cause.

**Comment by pgfearo** [comment]
Sorry, I'd coded the fix before seeing your PR. 
Your PR converted the path to a URI to resolve the issue. My fix builds a URI in the first place starting with the extension URI rather than the extension path. Both approaches seem to achieve the same result.

I've published the fix (Release 0.0.7) but please let me know if you still encounter problems.

**Comment by jgonzalez-stw** [comment]
Your fix is working fine, thanks!
